import React, { useRef, useState, useEffect } from 'react';
import html2canvas from 'html2canvas';
import type { Recipe, UiText } from '../types';
import FileTextIcon from './icons/FileTextIcon';
import ShareIcon from './icons/ShareIcon';
import ImageIcon from './icons/ImageIcon';
import RecipeImageExport from './RecipeImageExport';

interface RecipeDisplayProps {
  recipe: Recipe;
  uiText: UiText;
}

const RecipeDisplay: React.FC<RecipeDisplayProps> = ({ recipe, uiText }) => {
  const recipeCardRef = useRef<HTMLDivElement>(null);
  const exportImageRef = useRef<HTMLDivElement>(null);
  const [isCopied, setIsCopied] = useState(false);
  const [isSavingImage, setIsSavingImage] = useState(false);
  
  const webShareSupported = typeof navigator !== 'undefined' && !!navigator.share;

  useEffect(() => {
    let timeout: number;
    if (isCopied) {
      timeout = window.setTimeout(() => setIsCopied(false), 2000);
    }
    return () => clearTimeout(timeout);
  }, [isCopied]);
  
  const formatRecipeAsText = (): string => {
    const title = `RECIPE: ${recipe.recipeName}\n\n`;
    const description = `DESCRIPTION:\n${recipe.description}\n\n`;
    const ingredientsHeader = `--------------------\n\n${uiText.recipeIngredients.toUpperCase()}:\n`;
    const ingredientsList = recipe.ingredients.map(i => `- ${i}`).join('\n');
    const instructionsHeader = `\n\n--------------------\n\n${uiText.recipeInstructions.toUpperCase()}:\n`;
    const instructionsList = recipe.instructions.map((step, index) => `${index + 1}. ${step}`).join('\n');
    const footer = `\n\n--------------------\n\nGenerated by Toma AI by Syafiq Haron\nhttps://toma-recipe.ai/`;
    return `${title}${description}${ingredientsHeader}${ingredientsList}${instructionsHeader}${instructionsList}${footer}`;
  };

  const handleDownloadTxt = () => {
    const textContent = formatRecipeAsText();
    const blob = new Blob([textContent], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${recipe.recipeName.toLowerCase().replace(/\s+/g, '_')}_recipe.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  const handleDownloadImage = async () => {
    if (!exportImageRef.current) return;
      
    setIsSavingImage(true);
    try {
        const canvas = await html2canvas(exportImageRef.current, {
            scale: 2,
            useCORS: true,
        });
        const image = canvas.toDataURL('image/png', 1.0);
        const link = document.createElement('a');
        link.href = image;
        link.download = `${recipe.recipeName.toLowerCase().replace(/\s+/g, '_')}_recipe.png`;
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
    } catch (error) {
        console.error('Error generating image:', error);
        alert('Sorry, there was an error creating the image.');
    } finally {
        setIsSavingImage(false);
    }
  };
  
  const handleShare = async () => {
    const shareText = formatRecipeAsText();
    if (webShareSupported) {
      try {
        await navigator.share({
          title: `Toma AI Recipe: ${recipe.recipeName}`,
          text: shareText,
          // url property is removed to prevent apps like Outlook from ignoring the text body
        });
      } catch (error) {
        // User might cancel the share, which throws an error.
        // We can log it but don't need to show an alert.
        console.log("Web Share API error:", error);
      }
    } else {
      // Fallback to clipboard for browsers that don't support Web Share API
      try {
        await navigator.clipboard.writeText(shareText);
        setIsCopied(true);
      } catch (error) {
        console.error("Error copying to clipboard:", error);
        alert("Failed to copy recipe to clipboard.");
      }
    }
  };

  const ExportButton: React.FC<{onClick: () => void, disabled?: boolean, icon: React.ReactNode, text: string}> = ({ onClick, disabled, icon, text }) => (
    <button
      onClick={onClick}
      disabled={disabled}
      className="flex items-center gap-2 px-4 py-2 bg-white/80 backdrop-blur-sm border border-gray-200/80 rounded-full shadow-md text-sm font-medium text-gray-700 hover:bg-white focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-emerald-500 transition-all disabled:opacity-50 disabled:cursor-wait"
    >
      {icon}
      <span>{text}</span>
    </button>
  );

  return (
    <>
      <div ref={recipeCardRef} className="max-w-4xl mx-auto mt-12 bg-white/70 backdrop-blur-sm p-6 md:p-10 rounded-2xl shadow-lg border border-white/80 animate-fadeInUp">
        <div className="text-center mb-8">
          <h2 className="text-4xl font-bold bg-gradient-to-r from-emerald-600 to-teal-500 bg-clip-text text-transparent pb-2">
            {recipe.recipeName}
          </h2>
          <p className="mt-2 text-gray-600 italic max-w-2xl mx-auto">{recipe.description}</p>
        </div>
        
        <div className="text-center my-8 py-4 border-y border-gray-200/80">
          <h4 className="text-sm font-bold uppercase text-gray-500 tracking-wider mb-4">{uiText.exportTitle}</h4>
          <div className="flex flex-wrap justify-center items-center gap-4">
              <ExportButton onClick={handleDownloadTxt} icon={<FileTextIcon className="w-5 h-5 text-emerald-700" />} text={uiText.saveAsText} />
              <ExportButton 
                  onClick={handleDownloadImage}
                  disabled={isSavingImage}
                  icon={<ImageIcon className="w-5 h-5 text-emerald-700" />} 
                  text={isSavingImage ? uiText.saveAsImageSaving : uiText.saveAsImage} 
              />
              <ExportButton onClick={handleShare} icon={<ShareIcon className="w-5 h-5 text-emerald-700" />} text={!webShareSupported && isCopied ? uiText.shareCopied : uiText.share} />
          </div>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
          <div className="bg-emerald-50/50 p-6 rounded-xl">
            <h3 className="text-2xl font-semibold mb-4 border-b-2 border-emerald-300 pb-2 text-emerald-800">{uiText.recipeIngredients}</h3>
            <ul className="list-disc list-inside space-y-3 text-gray-700">
              {recipe.ingredients.map((ingredient, index) => (
                <li key={index}>{ingredient}</li>
              ))}
            </ul>
          </div>
          
          <div className="bg-emerald-50/50 p-6 rounded-xl">
            <h3 className="text-2xl font-semibold mb-4 border-b-2 border-emerald-300 pb-2 text-emerald-800">{uiText.recipeInstructions}</h3>
            <ol className="list-decimal list-inside space-y-4 text-gray-700 leading-relaxed">
              {recipe.instructions.map((step, index) => (
                <li key={index}>{step}</li>
              ))}
            </ol>
          </div>
        </div>
      </div>
      
      {/* Hidden component for clean image export */}
      <div className="absolute -left-[9999px] -top-[9999px]">
        <RecipeImageExport recipe={recipe} ref={exportImageRef} />
      </div>
    </>
  );
};

export default RecipeDisplay;