import React, { forwardRef } from 'react';
import type { Recipe } from '../types';

interface RecipeImageExportProps {
  recipe: Recipe;
}

const RecipeImageExport = forwardRef<HTMLDivElement, RecipeImageExportProps>(({ recipe }, ref) => {
  return (
    <div 
      ref={ref} 
      className="w-[800px] bg-white p-12 text-gray-800"
      style={{ fontFamily: "'Poppins', sans-serif" }}
    >
      <div className="text-center mb-8">
        <h1 className="text-4xl font-bold text-emerald-700 mb-2">{recipe.recipeName}</h1>
        <p className="text-gray-600 italic max-w-2xl mx-auto">{recipe.description}</p>
      </div>

      <div className="grid grid-cols-2 gap-8">
        <div>
          <h2 className="text-2xl font-semibold mb-4 border-b-2 border-emerald-300 pb-2 text-emerald-800">Ingredients</h2>
          <ul className="list-disc list-inside space-y-2 text-gray-700">
            {recipe.ingredients.map((ingredient, index) => (
              <li key={`ing-${index}`}>{ingredient}</li>
            ))}
          </ul>
        </div>
        
        <div>
          <h2 className="text-2xl font-semibold mb-4 border-b-2 border-emerald-300 pb-2 text-emerald-800">Instructions</h2>
          <ol className="list-decimal list-inside space-y-3 text-gray-700 leading-relaxed">
            {recipe.instructions.map((step, index) => (
              <li key={`inst-${index}`}>{step}</li>
            ))}
          </ol>
        </div>
      </div>
      
      <footer className="mt-12 pt-4 text-center border-t border-gray-200">
        <p className="text-sm text-gray-500">
          Generated by Toma AI by Syafiq Haron
        </p>
      </footer>
    </div>
  );
});

export default RecipeImageExport;
