import React, { forwardRef } from 'react';
import type { Recipe, ExportImageLayout, UiText } from '../types';

interface RecipeImageExportProps {
  recipe: Recipe;
  layout?: ExportImageLayout;
  uiText: UiText;
}

const RecipeImageExport = forwardRef<HTMLDivElement, RecipeImageExportProps>(({ recipe, layout = 'desktop', uiText }, ref) => {
  const isMobile = layout === 'mobile';

  // Dynamic styles based on layout
  const containerClasses = isMobile 
    ? "w-[450px] p-8" 
    : "w-[800px] p-12";
  const titleClasses = isMobile 
    ? "text-3xl" 
    : "text-4xl";
  const contentContainerClasses = isMobile 
    ? "flex flex-col gap-6" 
    : "grid grid-cols-2 gap-8";
  const sectionTitleClasses = isMobile 
    ? "text-xl" 
    : "text-2xl";

  return (
    <div 
      ref={ref} 
      className={`bg-white text-gray-800 ${containerClasses}`}
      style={{ fontFamily: "'Poppins', sans-serif" }}
    >
      <div className="text-center mb-8">
        <h1 className={`font-bold text-emerald-700 mb-2 ${titleClasses}`}>{recipe.recipeName}</h1>
        <p className="text-gray-600 italic max-w-2xl mx-auto">{recipe.description}</p>
      </div>

      <div className={contentContainerClasses}>
        <div>
          <h2 className={`font-semibold mb-4 border-b-2 border-emerald-300 pb-2 text-emerald-800 ${sectionTitleClasses}`}>Ingredients</h2>
          <ul className="list-disc list-inside space-y-2 text-gray-700">
            {recipe.ingredients.map((ingredient, index) => (
              <li key={`ing-${index}`}>{ingredient}</li>
            ))}
          </ul>
        </div>
        
        <div>
          <h2 className={`font-semibold mb-4 border-b-2 border-emerald-300 pb-2 text-emerald-800 ${sectionTitleClasses}`}>Instructions</h2>
          <ol className="list-decimal list-inside space-y-3 text-gray-700 leading-relaxed">
            {recipe.instructions.map((step, index) => (
              <li key={`inst-${index}`}>{step}</li>
            ))}
          </ol>
        </div>
      </div>
      
      <div className="mt-8 text-center">
        <h3 className="text-2xl font-bold text-emerald-700 flex items-center justify-center gap-2">
            <span>🍅</span>
            <span>Toma</span>
        </h3>
        <p className="text-gray-500 text-sm mt-1">{uiText.tagline}</p>
      </div>

      <footer className="mt-2 pt-2 text-center border-t border-gray-200">
        <p className="text-sm text-gray-500">
          Generated by Toma AI by Syafiq Haron
        </p>
      </footer>
    </div>
  );
});

export default RecipeImageExport;